site_name: Leo Li's Notebook
theme: 
  name: material
  logo: ./feather-solid.svg
  palette:
    primary: custom
    accent: deep purple

  font:
    text: Nunito
    code: Source Code Pro
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
  icon:
    repo: fontawesome/brands/github
  nav:
    - Home: index.md
    - ZJU CS courses:
        - test.md
        - Python: python.md

extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
repo_url: https://github.com/Leo11-strive/Leo-s-Notebook
repo_name: Leo Li's Notebook  
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.snippets
  - def_list
  - footnotes
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - md_in_html
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem

      
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details

  - pymdownx.tasklist:
      clickable_checkbox: true
  
  - toc:
      permalink: true
      title: On this page
  - tables
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  