site_name: My Docs

theme: 
  name: material
  palette:
    primary: cyan
    accent: deep purple
  font:
    text: Nunito
    code: Source Code Pro
  features:
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
repo_url: https://github.com/Leo11-strive/Leo-s-Notebook
repo_name: Leo Li's Notebook  
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.snippets
