site_name: Leo Li's Notebook  
site_author: Leo Li
theme: 
  name: material

  palette:
    - scheme: default
      primary: cyan
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: brown
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
 
  font:
    text: Merriweather
    code: JetBrains Mono
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    # - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中 
  icon:
    repo: fontawesome/brands/github
    logo: material/library-shelves
  extra:
    analytics: 
      feedback:
        title: Was this page helpful?
        ratings:
          - icon: material/emoticon-happy-outline
            name: This page was helpful
            data: 1
            note: >-
              Thanks for your feedback!
          - icon: material/emoticon-sad-outline
            name: This page could be improved
            data: 0
            note: >- 
              Thanks for your feedback! Help us improve this page by
              using our <a href="..." target="_blank" rel="noopener">feedback form</a>.




repo_url: https://github.com/Leo11-strive/Leo-s-Notebook
repo_name: Leo Li's Notebook  
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.snippets
  - def_list
  - footnotes
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - md_in_html
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem

      
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.tasklist:
      clickable_checkbox: true
  
  - toc:
      permalink: true
      title: On this page
  - tables
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js  
extra:
  analytics:
    provider: google
    property: G-4P08GMSPJM
    feedback:
      title: BOOST ME UP!
      ratings:
        - icon: fontawesome/regular/hand-back-fist
          name: BOOST ME UP！
          data: 1
          note: >-
            <center> 难道说……你愿意给我加一颗星吗！🫣 </center>


  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Leo11-stivebuil
      name: Github
 
copyright: 'Copyright &copy 2024 Leo Li'
      
  